### ISSUE TITLE
How to automatically create a chain of links?

### ISSUE THREAD

**Issue by dimensi** [magicznyleszek/hashtabber#1]
> You can chain parameters in links: #foo=2&bar=1&fum=baz&qux=2&zot=3, to switch tabs for all instances of HashTabber simultaneously  

How to make sure that the link is automatically built in the # foo = bar & = bar = foo
I create tabs in tabs, how do I make the links were for tabs were in the form of chains?

I use google translate, sorry and thank you in advance!
Great job and plugin as a whole!

**Comment by magicznyleszek** [comment]
Unfortunately there is no mechanism for href links to identify if there are other instances - in other words: the script knows which tab to switch from the url (**it will not "reset" tabs if they are not in the url parameters**), but it will not keep the information about all other tabs in the url.

You could dynamically build whole chain hash parameters on every hash change like this:
1. hash changes (via `<a href>` link or whatever)
2. loop through all instances of hashTabber in JS
3. get current tab and build whole chain string
4. set hash

**Comment by dimensi** [comment]
I don't know english and javascript( I asked for help on the forum and gave me your script with "bike".

```
...
    this.helpers = {
        hashProber: function () {
            // get hash from window location and remove # character
            var hash = String(window.location.hash.replace('#', ''));
            hash = decodeURIComponent(hash);
            var outcome = false;
            // if hash not empty
            // split it to array of parameters by "=" and "&"
            if (hash.length !== 0) {
                outcome = hash.split(/\=|&/);
            }
            return outcome;
        },
...
...
        tabSwiper: function (options, hashArray) {
            var a, b, c;
            var parameter;
            var value;
            var tabName;
            var tabberNavList;
            var tabberDataList;
            var hash, subtab;
            // loop through all hash parameters (every second item)
            for (a = 0; a < hashArray.length; a += 2) {
                // set the parameter and value
                parameter = hashArray[a];
                value = hashArray[a + 1];
                // add subtab support
                hash = (parameter = (hash = subtab == parameter ? hash : '') + parameter) + '=' + (subtab = value) + '&';
                // set the hash parameter
                tabName = '';
...
```

And subtab to attribute necessary to write `data-hashtabber-id="foo=bar&bar"` and then begin to build links.
I am satisfied with this decision, but I do not think you'll like it.
