### ISSUE TITLE
Open first tab, without define "data-hashtabber-default"

### ISSUE THREAD

**Issue by nimrodwhite** [magicznyleszek/hashtabber#2]
Is it possible to open first tab by default, if no any hash? My tabs ID is very difficult, and i can't to transfer this ID to script.
data-hashtabber-default = "0" does not works

**Comment by magicznyleszek** [comment]
I think that if you don't add `data-hashtabber-default` attribute, the first tab will be selected by default :) Sorry I haven't used this for a while
