### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by CoreyWycliffe** [magicznyleszek/hashtabber#3]
It might be nice to have this package available on https://www.npmjs.com/. That way we could use npm or yarn to install this as a dependency. Also, to have this available on a CDN. What do you think? I think a package.json file has to be created to make that happen.

**Comment by magicznyleszek** [comment]
@CoreyWycliffe This is generally a good idea, but I don't think I would find time to do this. This is 6 years old code and I've moved away from using this plugin for myself so there is no real drive for me here, sorry. Maybe you would like to take it over and make it appear on npm?

**Comment by CoreyWycliffe** [comment]
@magicznyleszek - is there an alternative that you use now? or are you just not using this type of library? I can try to see if I can make the package.json needed

**Comment by CoreyWycliffe** [comment]
https://www.npmjs.com/package/hashtabber
